use serde::{Deserialize, Serialize};

#[derive(Debug, Serialize, Deserialize, Clone)]
pub struct Stats {
    #[serde(rename = "FlatHPPoolMod")]
    pub flat_hp_pool_mod: f32,
    #[serde(rename = "rFlatHPModPerLevel")]
    pub r_flat_hp_mod_per_level: f32,
    #[serde(rename = "FlatMPPoolMod")]
    pub flay_mp_pool_mod: f32,
    #[serde(rename = "rFlatMPModPerLevel")]
    pub r_flat_mp_mod_per_level: f32,
    #[serde(rename = "PercentHPPoolMod")]
    pub percent_hp_pool_mod: f32,
    #[serde(rename = "PercentMPPoolMod")]
    pub percent_mp_pool_mod: f32,
    #[serde(rename = "FlatHPRegenMod")]
    pub flat_hp_regen_mod: f32,
    #[serde(rename = "rFlatHPRegenModPerLevel")]
    pub r_flat_hp_regen_mod_per_level: f32,
    #[serde(rename = "PercentHPRegenMod")]
    pub percent_hp_regen_mod: f32,
    #[serde(rename = "FlatMPRegenMod")]
    pub flat_mp_regen_mod: f32,
    #[serde(rename = "rFlatMPRegenModPerLevel")]
    pub r_flat_mp_regen_mod_per_level: f32,
    #[serde(rename = "PercentMPRegenMod")]
    pub percent_mp_regen_mod: f32,
    #[serde(rename = "FlatArmorMod")]
    pub flat_armor_mod: f32,
    #[serde(rename = "rFlatArmorModPerLevel")]
    pub r_flat_armor_mod_per_level: f32,
    #[serde(rename = "PercentArmorMod")]
    pub percent_armor_mod: f32,
    #[serde(rename = "rFlatArmorPenetrationMod")]
    pub r_flat_armor_penetration_mod: f32,
    #[serde(rename = "rFlatArmorPenetrationModPerLevel")]
    pub r_flat_armor_penetration_mod_per_level: f32,
    #[serde(rename = "rPercentArmorPenetrationMod")]
    pub r_percent_armor_penetration_mod: f32,
    #[serde(rename = "rPercentArmorPenetrationModPerLevel")]
    pub r_percent_armor_penetration_mod_per_level: f32,
    #[serde(rename = "FlatPhysicalDamageMod")]
    pub flat_physical_damage_mod: f32,
    #[serde(rename = "rFlatPhysicalDamageModPerLevel")]
    pub r_flat_physical_damage_mod_per_level: f32,
    #[serde(rename = "PercentPhysicalDamageMod")]
    pub percent_physical_damage_mod: f32,
    #[serde(rename = "FlatMagicDamageMod")]
    pub flat_magic_damage_mod: f32,
    #[serde(rename = "rFlatMagicDamageModPerLevel")]
    pub r_flat_magic_damage_mod_per_level: f32,
    #[serde(rename = "PercentMagicDamageMod")]
    pub percent_magic_damage_mod: f32,
    #[serde(rename = "FlatMovementSpeedMod")]
    pub flat_movement_speed_mod: f32,
    #[serde(rename = "rFlatMovementSpeedModPerLevel")]
    pub r_flat_movement_speed_mod_per_level: f32,
    #[serde(rename = "PercentMovementSpeedMod")]
    pub percent_movement_speed_mod: f32,
    #[serde(rename = "rPercentMovementSpeedModPerLevel")]
    pub r_percent_movement_speed_mod_per_level: f32,
    #[serde(rename = "FlatAttackSpeedMod")]
    pub flat_attack_speed_mod: f32,
    #[serde(rename = "PercentAttackSpeedMod")]
    pub percent_attack_speed_mod: f32,
    #[serde(rename = "rPercentAttackSpeedModPerLevel")]
    pub r_percent_attack_speed_mod_per_level: f32,
    #[serde(rename = "rFlatDodgeMod")]
    pub r_flat_dodge_mod: f32,
    #[serde(rename = "rFlatDodgeModPerLevel")]
    pub r_flat_dodge_mod_per_level: f32,
    #[serde(rename = "PercentDodgeMod")]
    pub percemt_dodge_mod: f32,
    #[serde(rename = "FlatCritChanceMod")]
    pub flat_crit_chance_mod: f32,
    #[serde(rename = "rFlatCritChanceModPerLevel")]
    pub r_flat_crit_chance_mod_per_level: f32,
    #[serde(rename = "PercentCritChanceMod")]
    pub percent_crit_chance_mod: f32,
    #[serde(rename = "FlatCritDamageMod")]
    pub flat_crit_damage_mod: f32,
    #[serde(rename = "rFlatCritDamageModPerLevel")]
    pub r_flat_crit_damage_mod_per_level: f32,
    #[serde(rename = "PercentCritDamageMod")]
    pub percent_crit_damage_mod: f32,
    #[serde(rename = "FlatBlockMod")]
    pub flat_block_mod: f32,
    #[serde(rename = "PercentBlockMod")]
    pub percent_block_mod: f32,
    #[serde(rename = "FlatSpellBlockMod")]
    pub flat_spell_block_mod: f32,
    #[serde(rename = "rFlatSpellBlockModPerLevel")]
    pub r_flat_spell_block_mod_per_level: f32,
    #[serde(rename = "PercentSpellBlockMod")]
    pub percent_spell_block_mod: f32,
    #[serde(rename = "FlatEXPBonus")]
    pub flat_exp_bonus: f32,
    #[serde(rename = "PercentEXPBonus")]
    pub percent_exp_bonus: f32,
    #[serde(rename = "rPercentCooldownMod")]
    pub r_percent_cooldown_mod: f32,
    #[serde(rename = "rPercentCooldownModPerLevel")]
    pub r_percent_cooldown_mod_per_level: f32,
    #[serde(rename = "rFlatTimeDeadMod")]
    pub r_flat_time_dead_mod: f32,
    #[serde(rename = "rFlatTimeDeadModPerLevel")]
    pub r_flat_time_dead_mod_per_level: f32,
    #[serde(rename = "rPercentTimeDeadMod")]
    pub r_percent_time_dead_mod: f32,
    #[serde(rename = "rPercentTimeDeadModPerLevel")]
    pub r_percent_time_dead_mod_per_level: f32,
    #[serde(rename = "rFlatGoldPer10Mod")]
    pub r_flat_gold_per_10_mod: f32,
    #[serde(rename = "rFlatMagicPenetrationMod")]
    pub r_flat_magic_penetration_mod: f32,
    #[serde(rename = "rFlatMagicPenetrationModPerLevel")]
    pub r_flat_magic_penetration_mod_per_level: f32,
    #[serde(rename = "rPercentMagicPenetrationMod")]
    pub r_percent_magic_penetration_mod: f32,
    #[serde(rename = "rPercentMagicPenetrationModPerLevel")]
    pub r_percent_magic_penetration_mod_per_level: f32,
    #[serde(rename = "FlatEnergyRegenMod")]
    pub flat_energy_regen_mod: f32,
    #[serde(rename = "rFlatEnergyRegenModPerLevel")]
    pub r_flat_energy_regen_mod_per_level: f32,
    #[serde(rename = "FlatEnergyPoolMod")]
    pub flat_energy_pool_mod: f32,
    #[serde(rename = "rFlatEnergyModPerLevel")]
    pub r_flat_energy_pool_mod_per_level: f32,
    #[serde(rename = "PercentLifeStealMod")]
    pub percent_life_steal_mod: f32,
    #[serde(rename = "PercentSpellVampMod")]
    pub percent_spell_vamp_mod: f32,
}
